export const marqueeItems = [
  'LangGraph',
  'Aurium AI',
  'Claude API',
  'RAG Pipelines',
  'FastAPI',
  'pgvector',
  'Multi-Agent',
  'BOTIQ AI',
];

export const hexSkills = [
  { icon: '🔗', name: 'LangChain' },
  { icon: '🔀', name: 'LangGraph' },
  { icon: '🧬', name: 'Claude API' },
  { icon: '⚡', name: 'OpenAI API' },
  { icon: '🤖', name: 'RAG Systems' },
  { icon: '✍', name: 'Prompt Eng.' },
  { icon: '🚀', name: 'FastAPI' },
  { icon: '🐍', name: 'Python' },
  { icon: '🗄', name: 'pgvector' },
  { icon: '📌', name: 'Qdrant' },
  { icon: '▲', name: 'Next.js' },
  { icon: '☁', name: 'AWS Cert.' },
];

export const skillGroups = [
  {
    label: 'AI / LLM',
    items: [
      'LangChain',
      'LangGraph',
      'Claude API',
      'OpenAI API',
      'RAG Systems',
      'Prompt Engineering',
    ],
  },
  {
    label: 'Backend / Data',
    items: [
      'FastAPI',
      'Python',
      'Supabase / pgvector',
      'Qdrant',
      'Pinecone',
      'PostgreSQL',
    ],
  },
  {
    label: 'Frontend / Tools',
    items: [
      'Next.js',
      'n8n Automation',
      'Docker',
      'Streamlit',
      'AWS (Certified)',
      'LangSmith',
    ],
  },
];

export const projects = [
  {
    num: '01',
    title: 'Aurium AI',
    desc: 'Australian tax SaaS · multi-tenant RAG · Claude Sonnet · pgvector',
    year: '2025',
    status: 'in-dev',
    featured: true,
    shortTags: ['SaaS', 'LangGraph', 'FastAPI'],
    goldTags: ['SaaS'],
    preview: '',
    links: {},
  },
  {
    num: '02',
    title: 'BOTIQ AI',
    desc: 'WhatsApp Business SaaS · menu bot · lead pipeline · Razorpay',
    year: '2025',
    status: 'live',
    shortTags: ['SaaS', 'FastAPI', 'WhatsApp'],
    goldTags: ['SaaS'],
    preview: 'assets/previews/botiq.gif',
    links: { github: 'https://github.com/TRUSHAKHACHARIYA/Whatsapp-Bot' },
  },
  {
    num: '03',
    title: 'DocWise',
    desc: 'Multi-document AI workspace · RAG · Claude · Pinecone · multi-tenant',
    year: '2025',
    status: 'live',
    shortTags: ['RAG', 'Claude', 'Next.js'],
    goldTags: ['SaaS'],
    preview: 'assets/previews/docwise.gif',
    links: { github: 'https://github.com/TRUSHAKHACHARIYA/DocWise' },
  },
  {
    num: '04',
    title: 'DocMind',
    desc: 'BYOK document Q&A · Ragie.ai · FastAPI · semantic search',
    year: '2025',
    status: 'in-dev',
    shortTags: ['RAG', 'BYOK', 'FastAPI'],
    goldTags: [],
    preview: '',
    links: {},
  },
  {
    num: '05',
    title: 'HIRE Framework',
    desc: 'AI recruiter evaluation · n8n workflows · LangChain scoring',
    year: '2024',
    status: 'in-dev',
    shortTags: ['n8n', 'LangChain', 'Agents'],
    goldTags: [],
    preview: '',
    links: {},
  },
  {
    num: '06',
    title: 'Resume Chatbot',
    desc: 'Multi-agent LangGraph · FastAPI · OpenAI/Claude · 7Span',
    year: '2025',
    status: 'archived',
    shortTags: ['LangGraph', 'FastAPI', 'NLP'],
    goldTags: [],
    preview: '',
    links: {},
  },
];

export const siteConfig = {
  email: 'khachariyatrusha@gmail.com',
  resumePath: 'assets/Trusha_Khachariya.pdf',
  siteUrl: 'https://portfolio-seven-phi-zyohdnoii5.vercel.app',
};
